"""Compute the real statistical tables for EXO-RANK and write them to
EXO_RANK_STATISTICAL_APPENDIX.md. Read-only on data. Run with anaconda python."""
import numpy as np, pandas as pd, re
from scipy.stats import spearmanr, pearsonr, mannwhitneyu, kruskal
import os

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
O = os.path.join(ROOT, "outputs")
def rd(f): return pd.read_excel(os.path.join(O, f)) if f.endswith("xlsx") else pd.read_csv(os.path.join(O, f), encoding="utf-8")

fs   = rd("final_score_calculation.csv")
afn  = rd("alphafold_normalized.csv")
ipae = rd("interface_pae.csv")[["Target No.","Group","interface_PAE"]]
dg   = rd("prodig_v1_parsed.xlsx").rename(columns={"Target No":"Target No.","ΔG (kcal/mol)":"dG"})
prod = rd("PRODIGY INFO.xlsx")
ss   = rd("string_score.csv")
bio  = rd("biological_feasibility_score.csv")

L = []  # markdown lines
def h(s): L.append("\n## "+s)
def p(s): L.append(s)
def mat(df, title):
    L.append(f"\n**{title}**\n")
    L.append(df.round(3).to_markdown())

L.append("# EXO-RANK — Statistical Appendix (computed from the actual data)\n")
L.append("*Auto-generated by scoring/build_stats_appendix.py. n varies by availability (stated per table).*")

# ---------- 1. AFS feature stats + correlation ----------
h("1. AlphaFold feature distributions & correlation (n = 200)")
af = afn.merge(ipae, on=["Target No.","Group"])
lo, hi = af.interface_PAE.min(), af.interface_PAE.max()
af["interface_PAE_N"] = 1 - (af.interface_PAE - lo)/(hi - lo)
feats = ["ipTM_N","pTM_N","interface_PAE_N","mean_pLDDT_N","median_PAE_N"]
desc = af[feats].describe().T[["mean","std","min","50%","max"]]
desc["skew"] = af[feats].skew()
mat(desc[["mean","std","skew","min","50%","max"]], "Descriptive statistics (normalized 0-1 features)")
mat(af[feats].corr(method="pearson"), "Pearson correlation")
mat(af[feats].corr(method="spearman"), "Spearman correlation")
p("\n*Read: ipTM ~ orthogonal to the rest; pTM/PAE/pLDDT form a correlated 'global-confidence' cluster; "
  "median PAE & interface PAE both retained for reference (AFS uses interface_PAE_N).*")

# ---------- 2. Source-level correlation (AFS, PS, SS, BS) ----------
h("2. Source-level correlation: AFS, PS, SS, BS (pairwise complete)")
d = fs.copy()
d["BSn"] = d["BS_flag"].map({"Low":0,"Medium":1,"High":2})
src = d[["AFS","PS","SS","BSn"]].rename(columns={"BSn":"BS"})
mat(src.corr(method="spearman"), "Spearman")
mat(src.corr(method="pearson"), "Pearson")
p(f"\nPairwise n: AFS-PS={d[['AFS','PS']].dropna().shape[0]}, AFS-SS={d[['AFS','SS']].dropna().shape[0]}, "
  f"PS-SS={d[['PS','SS']].dropna().shape[0]}. *Near-zero AFS/PS/SS correlations justify combining them.*")

# ---------- 3. Missingness & coverage ----------
h("3. Missingness & coverage (n = 200)")
miss = pd.DataFrame({
    "present":[d.AFS.notna().sum(), d.PS.notna().sum(), d.SS.notna().sum()],
    "missing":[d.AFS.isna().sum(), d.PS.isna().sum(), d.SS.isna().sum()],
}, index=["AFS","PS","SS"])
mat(miss, "Availability per source")
covd = d.Coverage.value_counts().sort_index()
p("\nCoverage distribution: " + ", ".join(f"{k} = {v}" for k,v in covd.items()))

# ---------- 4. PRODIGY redundancy ----------
h("4. PRODIGY redundancy (n = 151 complete)")
CAT=["Charged- charged contacts","charged- polar contacts","charged- apolar contacts",
     "polar- polar contacts","apolar- polar contacts","apolar- apolar contacts"]
for c in ["Intermolecular contacts","NIS residues (% of apolar NIS residues)","NIS residues (% of charged NIS residues)"]+CAT:
    prod[c]=pd.to_numeric(prod[c],errors="coerce")
pr = prod.merge(dg[["Target No.","Group","dG"]], on=["Target No.","Group"]).dropna(subset=["dG","Intermolecular contacts"])
pr["logKd"]=np.log10(pd.to_numeric(dg.set_index(["Target No.","Group"]).reindex(list(zip(pr["Target No."],pr.Group)))["Kd (M)"].values if "Kd (M)" in dg.columns else np.nan, errors="coerce")) if "Kd (M)" in dg.columns else np.nan
prc = pd.DataFrame({
    "vs dG (Pearson)":[
        pearsonr(pr.dG, pr["Intermolecular contacts"])[0],
        pearsonr(pr.dG, pr["NIS residues (% of apolar NIS residues)"])[0],
        pearsonr(pr.dG, pr["NIS residues (% of charged NIS residues)"])[0],
    ]}, index=["Intermolecular contacts","% NIS apolar","% NIS charged"])
mat(prc, "ΔG vs PRODIGY inputs (Pearson r)")
# R^2 of dG ~ 6 contacts + 2 NIS
X = np.column_stack([np.ones(len(pr))]+[pr[c] for c in CAT]+[pr["NIS residues (% of apolar NIS residues)"], pr["NIS residues (% of charged NIS residues)"]])
beta,*_=np.linalg.lstsq(X, pr.dG.values, rcond=None); pred=X@beta
r2=1-((pr.dG-pred)**2).sum()/((pr.dG-pr.dG.mean())**2).sum()
sp=spearmanr(pr.dG, pr["Intermolecular contacts"]).correlation
p(f"\nΔG vs contacts: Pearson **{pearsonr(pr.dG,pr['Intermolecular contacts'])[0]:.3f}**, Spearman **{sp:.3f}**.")
p(f"ΔG reconstructed from 6 contact categories + 2 NIS: **R² = {r2:.4f}** → ΔG carries all of it (PS uses ΔG alone).")
ddesc = pr[["dG","Intermolecular contacts"]].describe().T[["min","50%","max","mean","std"]]
ddesc["skew"]=pr[["dG","Intermolecular contacts"]].skew()
mat(ddesc, "ΔG & contacts distribution")

# ---------- 5. STRING channels vs combined ----------
h("5. STRING channels vs combined score (n = 64 scored)")
have = ss[ss.STRING_combined.notna()].copy()
for c in ["experimental","database","textmining","coexpression"]: have[c]=have[c].fillna(0.0)
srow = pd.DataFrame({"Pearson vs combined":[
    pearsonr(have.STRING_combined, have.textmining)[0],
    pearsonr(have.STRING_combined, have.experimental)[0],
    pearsonr(have.STRING_combined, have.database)[0],
    pearsonr(have.STRING_combined, have.coexpression)[0],
]}, index=["text-mining","experimental","database","co-expression"])
mat(srow, "Channel vs combined")
prob = 1-(1-have[["experimental","database","textmining","coexpression"]]).prod(axis=1)
p(f"\ncombined vs 1−∏(1−channels): Pearson **{pearsonr(have.STRING_combined,prob)[0]:.3f}** → channels already inside combined.")
p(f"Dominant channel among scored pairs: " + ", ".join(f"{k}={v}" for k,v in have.dominant_channel.value_counts().items()))

# ---------- 6. Group A/B ----------
h("6. Group A vs B (sanity check only)")
rows=[]
for c in ["TPS","AFS","PS","SS"]:
    a=d[d.Group_AB=="A"][c].dropna(); b=d[d.Group_AB=="B"][c].dropna()
    U,pv=mannwhitneyu(a,b); cliff=2*U/(len(a)*len(b))-1
    rows.append([c, round(a.median(),3), round(b.median(),3), round(pv,4), round(cliff,2)])
mat(pd.DataFrame(rows, columns=["metric","A median","B median","MWU p","Cliff d"]).set_index("metric"), "Group A vs B")
p(f"\nShortlist enrichment: A = {(d[(d.Group_AB=='A')&(d.BS_flag!='Low')&(d.Coverage!='1/3')].shape[0])}/100, "
  f"B = {(d[(d.Group_AB=='B')&(d.BS_flag!='Low')&(d.Coverage!='1/3')].shape[0])}/100 preferred.")

# ---------- 7. BS distribution + circularity ----------
h("7. Biological feasibility (BS) & circularity")
p("BS per candidate: " + ", ".join(f"{k}={v}" for k,v in bio.BS_flag.value_counts().items()))
a=d[d.Group_AB=="A"].BSn.dropna(); b=d[d.Group_AB=="B"].BSn.dropna()
U,pv=mannwhitneyu(a,b); p(f"\nBS vs Group A/B: Cliff d = **{2*U/(len(a)*len(b))-1:+.2f}** (p={pv:.1e}) → BS strongly tracks the selection split (why BS is a FILTER, not a term).")
kw = kruskal(*[d[d.BS_flag==k].TPS.dropna() for k in ["Low","Medium","High"]]).pvalue
p(f"Kruskal–Wallis, TPS across BS categories: p = {kw:.4f}.")

# ---------- 8. Weight sensitivity (TPS) ----------
h("8. TPS weight-sensitivity (n = 200)")
SRC=["AFS","PS","SS"]
def tps(row,w):
    av=[(s,row[s]) for s in SRC if pd.notna(row[s])]
    return sum(w[s]*v for s,v in av)/sum(w[s] for s,_ in av) if av else np.nan
SCH={"equal":(1/3,1/3,1/3),"0.50/0.30/0.20":(.5,.3,.2),"0.50/0.20/0.30":(.5,.2,.3),
     "0.40/0.35/0.25":(.4,.35,.25),"0.40/0.30/0.30":(.4,.3,.3)}
T={n: d.apply(lambda r: tps(r, {"AFS":a,"PS":b,"SS":c}), axis=1) for n,(a,b,c) in SCH.items()}
rows=[]
for n in SCH:
    rho=spearmanr(T["equal"],T[n]).correlation
    t10=len(set(T["equal"].nlargest(10).index)&set(T[n].nlargest(10).index))
    t20=len(set(T["equal"].nlargest(20).index)&set(T[n].nlargest(20).index))
    rows.append([n, round(rho,3), f"{t10}/10", f"{t20}/20"])
mat(pd.DataFrame(rows, columns=["scheme (AFS/PS/SS)","Spearman vs equal","top-10","top-20"]).set_index("scheme (AFS/PS/SS)"), "Sensitivity to TPS weights")

# ---------- 9. Leave-one-source-out ----------
h("9. Leave-one-source-out (Spearman vs full TPS)")
def sub(row, srcs):
    av=[row[s] for s in srcs if pd.notna(row[s])]
    return np.mean(av) if av else np.nan
rows=[]
for combo,label in [(["AFS"],"AFS only"),(["PS"],"PS only"),(["SS"],"SS only"),
                    (["AFS","PS"],"AFS+PS"),(["AFS","SS"],"AFS+SS"),(["PS","SS"],"PS+SS")]:
    col=d.apply(lambda r: sub(r,combo), axis=1)
    m=pd.concat([d.TPS,col],axis=1).dropna()
    rows.append([label, round(spearmanr(m.iloc[:,0],m.iloc[:,1]).correlation,3), len(m)])
mat(pd.DataFrame(rows, columns=["variant","Spearman vs full TPS","n"]).set_index("variant"), "Source contribution")

open(os.path.join(ROOT,"EXO_RANK_STATISTICAL_APPENDIX.md"),"w",encoding="utf-8").write("\n".join(L)+"\n")
print("Wrote EXO_RANK_STATISTICAL_APPENDIX.md")
print("\n".join(L))
